/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package team;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanjay
 */
public class taxcal1 extends javax.swing.JFrame {
    
    public static String fullname;


    Double Salary;
    Double Rental;
    Double PGBP;
    Double Capital_Gain;
    Double Other_S;
    public static int totalIncome1;

    public taxcal1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public String getname_off() {
        return name_off.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salaryLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        housePropertyField = new javax.swing.JTextField();
        businessProfessionField = new javax.swing.JTextField();
        capitalGain = new javax.swing.JTextField();
        otherSources = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nextbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        name_off = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salaryLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        salaryLabel.setText("Salary (Annual):");
        getContentPane().add(salaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("House Property (Rental):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Business and Profession (PGBP):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Capital Gain:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Other Sources:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));
        getContentPane().add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 150, -1));
        getContentPane().add(housePropertyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 150, -1));
        getContentPane().add(businessProfessionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 150, -1));
        getContentPane().add(capitalGain, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 150, -1));
        getContentPane().add(otherSources, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 150, -1));

        jButton1.setBackground(new java.awt.Color(221, 24, 24));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\back.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, 100));

        nextbutton.setBackground(new java.awt.Color(221, 24, 24));
        nextbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\next.png")); // NOI18N
        nextbutton.setBorder(null);
        nextbutton.setBorderPainted(false);
        nextbutton.setContentAreaFilled(false);
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(nextbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 100, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gross Total Income:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full name (as per official documents):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Aadhar Card Number:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PAN Card number:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 200, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\icons8-info-50.png")); // NOI18N
        jButton2.setText("Info");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 130, 70));

        name_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_offActionPerformed(evt);
            }
        });
        getContentPane().add(name_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 150, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 150, -1));

        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        getContentPane().add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\Pure Lust.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new homePage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
        if(salaryField.getText().isEmpty() || housePropertyField.getText().isEmpty() || businessProfessionField.getText().isEmpty() || capitalGain.getText().isEmpty() || otherSources.getText().isEmpty() || aadhar.getText().isEmpty() || name_off.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill all the required fields.");
        }
        else{
        totalIncome1 = (
            Integer.parseInt(salaryField.getText()) +
            Integer.parseInt(housePropertyField.getText()) +
            Integer.parseInt(businessProfessionField.getText()) +
            Integer.parseInt(capitalGain.getText()) +
            Integer.parseInt(otherSources.getText())
        );
        taxcal2 page = new taxcal2();
        page.setVisible(true);
        page.pack();
        page.setLocationRelativeTo(null);
        this.dispose();

        System.out.println("totalIncome1: " + totalIncome1);
        fullname = name_off.getText();
    }
    }//GEN-LAST:event_nextbuttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void name_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_offActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_offActionPerformed

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new info11().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

//    public int totin1() {
//        int x=0;
//        x = totalIncome1;
//        return x;
//    }
    
//    private void nextBtn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nextBtn1ActionPerformed
//        if(salaryField.getText().isEmpty() || housePropertyField.getText().isEmpty() || businessProfessionField.getText().isEmpty() || capitalGain.getText().isEmpty() || otherSources.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"The Field is Empty");
//        }
//        else{
//        totalIncome1 = (
//            Integer.parseInt(salaryField.getText()) +
//            Integer.parseInt(housePropertyField.getText()) +
//            Integer.parseInt(businessProfessionField.getText()) +
//            Integer.parseInt(capitalGain.getText()) +
//            Integer.parseInt(otherSources.getText())
//        );
//        taxcal2 page = new taxcal2();
//        page.setVisible(true);
//        page.pack();
//        page.setLocationRelativeTo(null);
//        this.dispose();
//
//        System.out.println("totalIncome1: " + totalIncome1);
//    }
//    }// GEN-LAST:event_nextBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taxcal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taxcal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taxcal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taxcal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taxcal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextField businessProfessionField;
    private javax.swing.JTextField capitalGain;
    private javax.swing.JTextField housePropertyField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField name_off;
    private javax.swing.JButton nextbutton;
    private javax.swing.JTextField otherSources;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    // End of variables declaration//GEN-END:variables
}
