/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package team;

import java.sql.*;
import javax.swing.JOptionPane;
import static team.taxcal1.totalIncome1;

/**
 *
 * @author Sanjay
 */
public class taxcal4 extends javax.swing.JFrame {
    
    
    public int getID() {
        try {
            ResultSet rs = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tms?zeroDateTimeBehavior=CONVERT_TO_NULL","root","Zebron1cs");
            String sql = "select max(id) from utr";
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                id = rs.getInt(1);
                id++;
            }
        }
        catch (Exception e) {
                e.printStackTrace();
        }
        return id;
    }
    
    int id=0;
    taxcal33 tc33 = new taxcal33();
    public static int totalIncomeFinal;
    public static String slab;
    public static double rate;
    public static double payableTax=0;
    public static int original_tax;
    public static double original_rate;
    public static double Tax_saved;
    

    /**
     * Creates new form taxcal4
     */
    public taxcal4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        oldtaxregimechkbox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Medical Insurance");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FD's investments");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("National Pension Scheme (NPS)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LIC/Other annuity plans");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Interest on Savings");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Interest on Education Loans");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contribution to Organisations");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Medical Expenses:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Age > 60");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age < 60");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\icons8-info-50.png")); // NOI18N
        jButton2.setText("Info");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 150, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 150, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 150, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 150, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 150, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 150, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 150, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 150, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 150, -1));

        oldtaxregimechkbox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        oldtaxregimechkbox.setForeground(new java.awt.Color(255, 255, 255));
        oldtaxregimechkbox.setText(" Old Tax Regime");
        oldtaxregimechkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldtaxregimechkboxActionPerformed(evt);
            }
        });
        getContentPane().add(oldtaxregimechkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 200, -1));

        jButton1.setBackground(new java.awt.Color(221, 24, 24));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\back.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 100, 100));

        submitBtn.setBackground(new java.awt.Color(221, 24, 24));
        submitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\submit.png")); // NOI18N
        submitBtn.setBorder(null);
        submitBtn.setBorderPainted(false);
        submitBtn.setContentAreaFilled(false);
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 100, 100));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Extra Savings");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 340, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\Pure Lust.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1030, 720));

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()|| jTextField6.getText().isEmpty()|| jTextField7.getText().isEmpty()|| jTextField8.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fill all required fields.");
        }
        else{
        int cc80 = tc33.c80 + (
            Integer.parseInt(jTextField1.getText()) +
            Integer.parseInt(jTextField2.getText()) +
            Integer.parseInt(jTextField3.getText()) +
            Integer.parseInt(jTextField4.getText()) +
            Integer.parseInt(jTextField5.getText()) +
            Integer.parseInt(jTextField6.getText()) +
            Integer.parseInt(jTextField7.getText()) +
            Integer.parseInt(jTextField8.getText()) +
            Integer.parseInt(jTextField9.getText())
        );
        
        if(oldtaxregimechkbox.isSelected()){
            //new code with conditions
        if (totalIncome1 >= 0 && totalIncome1 <= 250000) {
            original_rate = 0;
        } else if (totalIncome1 <= 500000) {
            original_rate = 5 ;
        } else if (totalIncome1 <= 750000) {
            original_rate = 20;
        } else if (totalIncome1 <= 1000000) {
            original_rate = 20;
        } else if (totalIncome1 <= 1250000) {
            original_rate = 30;
        } else if (totalIncome1 <= 1500000) {
            original_rate = 30;
        } else {
            original_rate = 30;
        }
             
        
        if (cc80 > 150000) totalIncomeFinal = tc33.totalIncome3 - 150000;
        else totalIncomeFinal = tc33.totalIncome3 - cc80;

        if (totalIncomeFinal >= 0 && totalIncomeFinal <= 250000) {
            slab = "0 to 250000";
            rate = 0;
        } else if (totalIncomeFinal <= 500000) {
            slab = "250001 to 500000";
            rate = 5;
        } else if (totalIncomeFinal <= 750000) {
            slab = "500001 to 750000";
            rate = 20;
        } else if (totalIncomeFinal <= 1000000) {
            slab = "750001 to 1000000";
            rate = 20;
        } else if (totalIncomeFinal <= 1250000) {
            slab = "1000001 to 1250000";
            rate = 30;
        } else if (totalIncomeFinal <= 1500000) {
            slab = "1250001 to 1500000";
            rate = 30;
        } else {
            slab = "above 1500001";
            rate = 30;
        }
            
        }
        else{
        if (totalIncome1 >= 0 && totalIncome1 <= 250000) {
            original_rate = 0;
        } else if (totalIncome1 <= 500000) {
            original_rate = 5;
        } else if (totalIncome1 <= 750000) {
            original_rate = 10;
        } else if (totalIncome1 <= 1000000) {
            original_rate = 15;
        } else if (totalIncome1 <= 1250000) {
            original_rate = 20;
        } else if (totalIncome1 <= 1500000) {
            original_rate = 25;
        } else {
            original_rate = 30;
        }
             
        
        if (cc80 > 150000) totalIncomeFinal = tc33.totalIncome3 - 150000;
        else totalIncomeFinal = tc33.totalIncome3 - cc80;

        if (totalIncomeFinal >= 0 && totalIncomeFinal <= 250000) {
            slab = "0 to 250000";
            rate = 0;
        } else if (totalIncomeFinal <= 500000) {
            slab = "250001 to 500000";
            rate = 5;
        } else if (totalIncomeFinal <= 750000) {
            slab = "500001 to 750000";
            rate = 10;
        } else if (totalIncomeFinal <= 1000000) {
            slab = "750001 to 1000000";
            rate = 15;
        } else if (totalIncomeFinal <= 1250000) {
            slab = "1000001 to 1250000";
            rate = 20;
        } else if (totalIncomeFinal <= 1500000) {
            slab = "1250001 to 1500000";
            rate = 25;
        } else {
            slab = "above 1500001";
            rate = 30;
        }
    }
        
        payableTax=rate*totalIncomeFinal/100;
        Tax_saved=original_rate*totalIncome1/100-(payableTax);
        
        System.out.println(totalIncomeFinal);
        System.out.println(slab);
        System.out.println(rate);
        System.out.println("Payable Tax: "+payableTax);
        System.out.println("Tax Saved: "+Tax_saved);
        System.out.println();
        new taxresult().setVisible(true);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tms?zeroDateTimeBehavior=CONVERT_TO_NULL","root","Zebron1cs");
            String sql = "insert into utr values(?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setInt(1, getID());
            stmt.setString(2, taxcal1.fullname);
            stmt.setString(3, String.valueOf(taxcal4.totalIncomeFinal));
            stmt.setString(4, String.valueOf(taxcal4.Tax_saved));
            stmt.setString(5, String.valueOf(taxcal4.payableTax));
            stmt.setString(6, String.valueOf(taxcal4.rate));
            
            stmt.executeUpdate();
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        }
        this.dispose();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new taxcal33().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oldtaxregimechkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldtaxregimechkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldtaxregimechkboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new info44().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taxcal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taxcal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taxcal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taxcal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception e) {
            e.printStackTrace();
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taxcal4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JCheckBox oldtaxregimechkbox;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
