/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package team;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanjay
 */
public class taxcal2 extends javax.swing.JFrame {
    public static int totalIncome2;
    taxcal1 tc1 = new taxcal1();

    /**
     * Creates new form taxcal2
     */
    public taxcal2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        houseRentalAllowanceField = new javax.swing.JTextField();
        houseLoanIntrestField = new javax.swing.JTextField();
        childrenEduAllowanceField = new javax.swing.JTextField();
        childHostelAllowanceField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        LTAField = new javax.swing.JTextField();
        nextBtn2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("House Rent Allowance:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("House Loan Interest:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 230, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Children's Education Allowance:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Children's Hostel Allowance:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LTA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 60, -1));

        houseRentalAllowanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseRentalAllowanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(houseRentalAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 190, -1));
        getContentPane().add(houseLoanIntrestField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 190, -1));
        getContentPane().add(childrenEduAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 190, -1));
        getContentPane().add(childHostelAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 190, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\icons8-info-50.png")); // NOI18N
        jButton2.setText("Info");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 140, 70));
        getContentPane().add(LTAField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 190, -1));

        nextBtn2.setBackground(new java.awt.Color(221, 24, 24));
        nextBtn2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\next.png")); // NOI18N
        nextBtn2.setToolTipText("");
        nextBtn2.setBorder(null);
        nextBtn2.setBorderPainted(false);
        nextBtn2.setContentAreaFilled(false);
        nextBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 100, 100));

        jButton1.setBackground(new java.awt.Color(221, 24, 24));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\back.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 100, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No-Tax Exemptions");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 500, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paarth Jha\\Desktop\\Work\\Java\\Project\\References\\icons\\Pure Lust.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new taxcal1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void houseRentalAllowanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseRentalAllowanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseRentalAllowanceFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new info22().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextBtn2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nextBtn2ActionPerformed
        if(LTAField.getText().isEmpty() || childHostelAllowanceField.getText().isEmpty() || childrenEduAllowanceField.getText().isEmpty() || houseLoanIntrestField.getText().isEmpty() || houseRentalAllowanceField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The Field is Empty");
        }
        else{
        totalIncome2 = (
            tc1.totalIncome1 -
            (
                Integer.parseInt(LTAField.getText()) +
                Integer.parseInt(childHostelAllowanceField.getText()) +
                Integer.parseInt(childrenEduAllowanceField.getText()) +
                Integer.parseInt(houseLoanIntrestField.getText()) +
                Integer.parseInt(houseRentalAllowanceField.getText())
            )
        );
        taxcal33 page = new taxcal33();
        page.setVisible(true);
        page.pack();
        page.setLocationRelativeTo(null);
        this.dispose();

        System.out.println("totalIncome2: " + totalIncome2);
    }
    }// GEN-LAST:event_nextBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taxcal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taxcal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taxcal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taxcal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taxcal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LTAField;
    private javax.swing.JTextField childHostelAllowanceField;
    private javax.swing.JTextField childrenEduAllowanceField;
    private javax.swing.JTextField houseLoanIntrestField;
    private javax.swing.JTextField houseRentalAllowanceField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton nextBtn2;
    // End of variables declaration//GEN-END:variables
}
